### ISSUE TITLE
TypeError: User is not a constructor

### ISSUE THREAD

**Issue by cCurmudgeon** [md-y/mangadex-full-api#32]
```/node_modules/mangadex-full-api/src/structure/group.js:71
            let user = new User(data.leader.id);
                       ^

TypeError: User is not a constructor
    at Group._parse (/node_modules/mangadex-full-api/src/structure/group.js:71:24)
    at /node_modules/mangadex-full-api/src/structure/group.js:146:22
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
```
This is while calling for group data.

```
    async function group(){
      api.agent.login(usrname, pass, false).then(async () => {
        var group = new api.Group();
        await group.fillByQuery("Doki Fansubs");
        console.log(`${group.title} | ${group.leader} | ${group.id}`);
        })
        }
```

**Comment by system32uwu** [comment]
Have you tried `**await** api.agent.login()` ?

**Comment by cCurmudgeon** [comment]
But I haven't added await for agent login for User, manga, etc.
But yeah I'll try thanks!

**Comment by md-y** [comment]
That might be another issue, but I had the same error even with the ```await```.

However, it should be fixed in the newest release.
