### ISSUE TITLE
"res.headers.set-cookie is not iterable" when using mangadex.cc

### ISSUE THREAD

**Issue by datWeazel** [md-y/mangadex-full-api#9]
```
[...]\Server\node_modules\mangadex-full-api\src\util.js:29
                for (let i of res.headers["set-cookie"]) {
                                         ^

TypeError: res.headers.set-cookie is not iterable
    at ClientRequest.<anonymous> ([...]\Server\node_modules\mangadex-full-api\src\util.js:29:42)
    at Object.onceWrapper (events.js:428:26)
    at ClientRequest.emit (events.js:321:20)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:603:27)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:119:17)
    at TLSSocket.socketOnData (_http_client.js:476:22)
    at TLSSocket.emit (events.js:321:20)
    at addChunk (_stream_readable.js:294:12)
    at readableAddChunk (_stream_readable.js:275:11)
    at TLSSocket.Readable.push (_stream_readable.js:209:10)
```

Using mangadex.org works fine (except search is not working. see: #8 )

**Comment by md-y** [comment]
_mangadex.cc_ now has DDoS-guard enabled, meaning the API will not work. Also, it simply redirects to _mangadex.org_ so I would recommend simply not using it. I will add an error for when someone uses _mangadex.cc_ in a later release.
